version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: rabbitmq
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      # Persistent storage
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - microservice_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  microservice_network:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local