spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
      database:  recommendations

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


server:
  port: 8083
