spring:
  application:
    name: ai-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
      database:  recommendations

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka


server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

germini:
  api:
    url: ${GERMINI_API_URL}
    key: ${GERMINI_API_KEY}
