### GET request to example server
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email" : "example@email.com",
  "password": "password123",
  "firstName": "John",
  "lastName": "Doe"
}